# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
  - name: EntryApi
    url: http://entry-api:3000/entry
    routes:
      - name: Entry
        paths:
          - /entry
  - name: ConsolidationApi
    url: http://consolidation-api:3000/consolidation
    routes:
      - name: Consolidation
        paths:
          - /consolidation